### ISSUE TITLE
Requesting your info on the univ/mobile/spyware soon as possible. I've been trying some others out that do nothing close to what they say an described info. I really need something that will work as stated and easily and discreetly installed on clients phone remotely as well as unnoticed. Thank you for your time,
          D.


### ISSUE THREAD

**Issue by Dunnsonn** [secret0truth0hackers/Universal-Mobile-Spyware#2]
Requesting your info on the univ/mobile/spyware soon as possible. I've been trying some others out that do nothing close to what they say an described info. I really need something that will work as stated and easily and discreetly installed on clients phone remotely as well as unnoticed. Thank you for your time,
          D.

**Comment by secret0truth0hackers** [comment]
Hello Dunson,

Our tool works discretely and was just updated to mirror target’s screen.

Frank.

**Comment by secret0truth0hackers** [comment]
Email: ***@***.***
